#!/usr/bin/env python3
"""
runbook-generator.py
--------------------
Generates a structured, actionable runbook from an incident postmortem.
Input: postmortem text (file or stdin)
Output: Markdown runbook ready for Confluence/Notion/GitHub

Usage:
    python runbook-generator.py --postmortem postmortem.txt --output runbook.md
    echo "DB connections maxed..." | python runbook-generator.py --stdin
"""

import anthropic
import argparse
import sys
from datetime import datetime, timezone

SYSTEM_PROMPT = """You are a senior SRE writing production runbooks.
Your runbooks are clear, scannable, and designed for the on-call engineer at 3am.
Every step is specific. Never write 'check the logs' — always specify which logs,
which query, what to look for. Include exact commands."""


def generate_runbook(postmortem_text: str, service_name: str = "unknown-service") -> str:
    client = anthropic.Anthropic()

    prompt = f"""Analyze this postmortem and generate a complete runbook.

<postmortem>
{postmortem_text}
</postmortem>

<service>{service_name}</service>
<generated>{datetime.now(timezone.utc).strftime('%Y-%m-%d')}</generated>

Generate a runbook in Markdown with these exact sections:

# Runbook: [Descriptive Title]

## Overview
- **Service**:
- **Alert Name**:
- **Severity**: P1/P2/P3
- **Generated**:

## Symptoms
What the on-call engineer will see (bullets)

## Detection
- Which alert fires
- Dashboard to check first (with example PromQL/LogQL query)
- Log query to run

## Triage Steps
Numbered, specific steps with exact commands. Include decision trees:
"If X, go to step N. If Y, escalate."

## Root Cause Categories
For each known cause:
### Cause: [Name]
- **Indicators**: How to confirm
- **Fix**: Exact steps + commands
- **Rollback**: How to undo if fix worsens things

## Escalation
- When to escalate (specific thresholds)
- Who to page (team names)
- What info to have ready

## Post-Incident Checklist
- [ ] Item 1
- [ ] Item 2

---
*Auto-generated by sre-ai-toolkit. Review before publishing.*"""

    message = client.messages.create(
        model="claude-opus-4-5",
        max_tokens=2048,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}]
    )
    return message.content[0].text


DEMO_POSTMORTEM = """
Incident: 2024-01-15 Database Connection Pool Exhaustion
Duration: 47 minutes (14:23 - 15:10 UTC)
Impact: Payment API returned 503 errors to ~12% of users

Timeline:
14:23 - Alert fires: payment-api error rate > 5%
14:31 - On-call acknowledges, begins investigation
14:45 - Root cause identified: connection pool exhausted (max 100 connections)
14:52 - Temporary fix: restarted 3 payment-api pods to release connections
15:01 - Permanent fix: increased pool size to 200, deployed
15:10 - Error rate returns to baseline

Root Cause: A slow query introduced in v2.4.1 (deployed 14:15 UTC) caused
connections to hold for 8-12s instead of <100ms. Under normal load this
exhausted the 100-connection pool within 8 minutes.

Contributing factors: No connection timeout configured, no pool exhaustion alert.

Action items:
- Add connection pool utilization alert at 80%
- Set query timeout to 5s
- Add slow query logging
"""

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate runbook from postmortem")
    parser.add_argument("--postmortem", help="Path to postmortem text file")
    parser.add_argument("--service", default="my-service")
    parser.add_argument("--output", default="runbook.md")
    parser.add_argument("--stdin", action="store_true")
    args = parser.parse_args()

    if args.stdin:
        postmortem = sys.stdin.read()
    elif args.postmortem:
        with open(args.postmortem) as f:
            postmortem = f.read()
    else:
        print("No postmortem provided — using demo data.")
        postmortem = DEMO_POSTMORTEM

    print(f"Generating runbook for {args.service}...")
    runbook = generate_runbook(postmortem, args.service)

    with open(args.output, "w") as f:
        f.write(runbook)

    print(f"Runbook saved to {args.output}")
    print(f"\n--- Preview ---\n{runbook[:600]}...")
